# Generated by Django 5.1.6 on 2025-02-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="URL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("long_url", models.URLField(unique=True)),
                ("short_code", models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
